-- CompletionRoute :: Adapters/WoWPro.lua
-- If the WoW-Pro addon is installed and enabled, expose its guides inside CompletionRoute at runtime.
-- Nothing is copied or redistributed: we read WoWPro.Guides from the user's own installation
-- (WoW-Pro guides are CC BY-NC-ND; this adapter is interoperability, guides stay in their addon).
-- The line syntax is identical to CompletionRoute's native format, so no conversion is needed.
local ADDON, NS = ...
local G = NS.Guide
NS.Adapters = NS.Adapters or {}
local A = {}
NS.Adapters.WoWPro = A

-- Import from the baked Guides/Imported_WoWPro.lua (generated by tools/export_guides.lua);
-- works with the WoW-Pro addon disabled or uninstalled.
function A.ImportStatic()
    local n = 0
    for _, g in ipairs(NS.ImportedWoWPro or {}) do
        -- per-flavor bake: only this client's era (untagged = any, from an older export)
        local flavorOK = (not g.flavor or g.flavor == "" or g.flavor == NS.flavor)
        if flavorOK and g.gid and g.text and not G.registry["wowpro:" .. g.gid] then
            if G.Register({
                id = "wowpro:" .. g.gid,
                name = g.name or g.zone or g.gid,
                type = g.type or "Leveling",
                zone = g.zone,
                faction = g.faction,
                minlevel = g.minl, maxlevel = g.maxl,
                next = g.next and ("wowpro:" .. g.next) or nil,
                author = g.author,
                source = "WoWPro",
                text = g.text,
            }) then n = n + 1 end
        end
    end
    if n > 0 then NS:Print(("Loaded %d baked WoW-Pro guide(s)."):format(n)) end
    return n
end

local imported = 0
function A.Import(verbose)
    if not _G.WoWPro or not WoWPro.Guides then if verbose then NS:Print("WoW-Pro not loaded; nothing to import.") end return 0 end
    local n = 0
    for gid, g in pairs(WoWPro.Guides) do
        if type(g) == "table" and g.sequence and not G.registry["wowpro:" .. gid] then
            local ok = G.Register({
                id = "wowpro:" .. gid,
                name = (g.name or g.zone or gid),
                type = g.guidetype or "Leveling",
                zone = g.zone,
                faction = g.faction,
                minlevel = g.startlevel, maxlevel = g.endlevel,
                next = g.nextGID and ("wowpro:" .. g.nextGID) or nil,
                author = g.author,
                source = "WoWPro",
                text = g.sequence,
            })
            if ok then n = n + 1 end
        end
    end
    imported = imported + n
    if verbose or n > 0 then NS:Print(("Imported %d WoW-Pro guide(s) (%d total)."):format(n, imported)) end
    return n
end

-- WoW-Pro registers guides at load; some modules load later (LoadOnDemand). Import at login and again shortly after.
NS:On("PLAYER_READY", function()
    A.ImportStatic()
    A.Import(false)
    NS:After(5, function() A.Import(false) end)
end)
NS:RegisterEvent("ADDON_LOADED", function(_, name)
    if name and name:find("^WoWPro") then NS:After(1, function() A.Import(false) end) end
end)
