#!/usr/bin/env python3
"""Generate OpenRoute/Data/Taxi_<flavor>.lua from wago.tools DB2 CSV exports.

Usage: python3 tools/gen_taxi.py [flavor build] ...
  e.g. python3 tools/gen_taxi.py tbc 2.5.6.69110 era 1.15.9.69109
With no args, regenerates from the CSVs already in tools/db2/<flavor>/.

CSV source (public game-data exports): https://wago.tools/db2/<Table>/csv?build=<build>
Tables: TaxiNodes, TaxiPath, TaxiPathNode.

Output per node:  {id, name, cont(instanceID), x, y (world coords), fac ('A','H','N')}
Output per path:  {from, to, cost(copper), len(yards along the real polyline)}
Faction from MountCreatureID_0 (Horde mount) / MountCreatureID_1 (Alliance mount).
"""
import csv, math, os, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "OpenRoute", "Data")
TABLES = ["TaxiNodes", "TaxiPath", "TaxiPathNode"]

def fetch(flavor, build):
    d = os.path.join(HERE, "db2", flavor); os.makedirs(d, exist_ok=True)
    for t in TABLES:
        url = f"https://wago.tools/db2/{t}/csv?build={build}"
        print("GET", url)
        urllib.request.urlretrieve(url, os.path.join(d, t + ".csv"))

def gen(flavor):
    d = os.path.join(HERE, "db2", flavor)
    nodes = {r["ID"]: r for r in csv.DictReader(open(os.path.join(d, "TaxiNodes.csv"), encoding="utf-8"))}
    paths = list(csv.DictReader(open(os.path.join(d, "TaxiPath.csv"), encoding="utf-8")))
    pn = {}
    for r in csv.DictReader(open(os.path.join(d, "TaxiPathNode.csv"), encoding="utf-8")):
        pn.setdefault(r["PathID"], []).append((int(r["NodeIndex"]), float(r["Loc_0"]), float(r["Loc_1"]), float(r["Loc_2"])))
    used = set()
    plines = []
    for p in paths:
        a, b = p["FromTaxiNode"], p["ToTaxiNode"]
        if a not in nodes or b not in nodes: continue
        pts = sorted(pn.get(p["ID"], []))
        L = 0.0
        for i in range(1, len(pts)):
            L += math.dist(pts[i-1][1:], pts[i][1:])
        if L == 0:  # no polyline: straight line
            na, nb = nodes[a], nodes[b]
            L = math.dist((float(na["Pos_0"]), float(na["Pos_1"])), (float(nb["Pos_0"]), float(nb["Pos_1"])))
        used.add(a); used.add(b)
        plines.append(f"  {{{a},{b},{int(p['Cost'] or 0)},{L:.0f}}},")
    nlines = []
    for nid in sorted(used, key=int):
        n = nodes[nid]
        h = n.get("MountCreatureID_0", "0") not in ("", "0")
        al = n.get("MountCreatureID_1", "0") not in ("", "0")
        fac = "N" if (h and al) else ("A" if al else ("H" if h else "N"))
        name = n["Name_lang"].replace("\\", "\\\\").replace('"', '\\"')
        nlines.append(f'  [{nid}]={{"{name}",{int(n["ContinentID"])},{float(n["Pos_0"]):.1f},{float(n["Pos_1"]):.1f},"{fac}"}},')
    os.makedirs(OUT, exist_ok=True)
    fn = os.path.join(OUT, f"Taxi_{flavor}.lua")
    with open(fn, "w", encoding="utf-8") as f:
        f.write("-- GENERATED by tools/gen_taxi.py from wago.tools DB2 exports. Do not edit by hand.\n")
        f.write("-- node = {name, continentInstanceID, worldX, worldY, faction A/H/N}; path = {fromID, toID, costCopper, lengthYards}\n")
        f.write("local _, NS = ...\nNS.TaxiData = NS.TaxiData or {}\n")
        f.write(f'NS.TaxiData["{flavor}"] = {{\n nodes = {{\n' + "\n".join(nlines) + "\n },\n paths = {\n" + "\n".join(plines) + "\n },\n}\n")
    print(f"{fn}: {len(nlines)} nodes, {len(plines)} paths")

if __name__ == "__main__":
    args = sys.argv[1:]
    if args:
        for i in range(0, len(args), 2):
            fetch(args[i], args[i+1]); gen(args[i])
    else:
        for fl in sorted(os.listdir(os.path.join(HERE, "db2"))):
            gen(fl)
