#!/usr/bin/env python3
# CompletionRoute :: tools/gen_completion_guides.py
# Copyright (c) 2026 Daniel Bates / BatesAI. All rights reserved.
# Licensed under PolyForm Noncommercial 1.0.0 + 10% commercial-revenue rider (see LICENSE).
# https://batesai.org  help@batesai.org
"""Generate the "completionist" guide sets from Blizzard client data (wago.tools DB2 exports):

    python3 tools/gen_completion_guides.py [retail] [mop]

  Guides/Imported_Achievements_<fl>.lua   one guide per achievement category (retail, mop).  Every
      achievement that is not a statistic becomes a block of steps: one per criterion (cap 60), then a
      FIXED "earn it" step.  A criterion that is "complete quest N" gets that quest's map location from
      the flavor's Imported_Quests_<fl>.lua, so the router can order those steps by travel time; the
      rest carry |ACH|<achievement>;<criteria-tree id>| and tick from GetAchievementCriteriaInfoByID.
  Guides/Imported_Storylines_retail.lua   one guide per QuestLine, quests in the client's OrderIndex
      order.  Each accept carries |PRE|<previous quest>| so the optimizer can interleave travel but can
      never break the story order.  Step lines (with locations) are reused from Imported_Quests_retail.
  Guides/Imported_Missions_retail.lua     one guide per mission table (WoD garrison + shipyard, Legion
      order hall, BfA war table, Shadowlands covenant table): a travel step to the table, then one
      note step per GarrMission row (|MISSION|id|) with followers, duration and cost.  Mission
      completion has no persistent client flag, so those steps are manual clicks.

Inputs: tools/db2/<fl>/{Achievement,Achievement_Category,Criteria,CriteriaTree}.csv,
tools/db2/retail/{QuestLine,QuestLineXQuest,GarrMission}.csv, tools/db2/questie_index.tsv (names).
Everything written is Blizzard/Questie-derived data: gitignored (Imported_*.lua); only this script ships.
"""
import csv, re, sys, collections
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB2 = ROOT / "tools" / "db2"
GUIDES = ROOT / "CompletionRoute" / "Guides"
MAX_CRIT = 60


def rows(fl, table):
    p = DB2 / fl / f"{table}.csv"
    return list(csv.DictReader(p.open(encoding="utf-8"))) if p.exists() else []


def clean(s):
    return re.sub(r"\s+", " ", (s or "").replace("|", "/")).strip()


def lua_str(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def questie_names():
    p = DB2 / "questie_index.tsv"
    out = {}
    if p.exists():
        for r in csv.DictReader(p.open(encoding="utf-8"), delimiter="\t"):
            out[int(r["qid"])] = (r["name"], r["faction"])
    return out


def quest_lines(fl):
    """qid -> [step lines] from Imported_Quests_<fl>.lua (the per-zone community quest guides)"""
    p = GUIDES / f"Imported_Quests_{fl}.lua"
    out = collections.defaultdict(list)
    if not p.exists():
        return out
    for line in p.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^[ACT] .*?\|QID\|(\d+)\|", line)
        if m:
            out[int(m.group(1))].append(line)
    return out


def located(lines, action_pref=("T", "A", "C")):
    """(M, Z) of the best located step among a quest's lines"""
    for a in action_pref:
        for l in lines:
            if l.startswith(a + " "):
                m = re.search(r"\|M\|([^|]+)\|Z\|([^|]+)\|", l)
                if m:
                    return m.group(1), m.group(2)
    return None


def header(fl, what):
    return [f"-- AUTO-GENERATED by tools/gen_completion_guides.py ({what}) from Blizzard client data",
            "-- (wago.tools DB2 exports).  Local use only - gitignored, do not redistribute.",
            "local _, NS = ...", f'if NS.flavor ~= "{fl}" then return end', "local R = NS.Guide.Register"]


def gen_achievements(fl, qnames):
    ach = [r for r in rows(fl, "Achievement") if not (int(r["Flags"] or 0) & 0x1)]
    if not ach:
        print(f"{fl}: no Achievement.csv - skipped")
        return
    cats = {int(r["ID"]): r for r in rows(fl, "Achievement_Category")}
    crit = {int(r["ID"]): r for r in rows(fl, "Criteria")}
    kids = collections.defaultdict(list)
    tree = {}
    for r in rows(fl, "CriteriaTree"):
        tree[int(r["ID"])] = r
        kids[int(r["Parent"])].append(r)
    for k in kids:
        kids[k].sort(key=lambda r: (int(r["OrderIndex"] or 0), int(r["ID"])))
    achname = {int(r["ID"]): clean(r["Title_lang"]) for r in ach}
    qlines = quest_lines(fl)

    def catpath(cid):
        parts, seen = [], set()
        while cid in cats and cid not in seen and cid != -1:
            seen.add(cid)
            parts.append(clean(cats[cid]["Name_lang"]))
            cid = int(cats[cid]["Parent"])
        return " - ".join(reversed(parts)) or "Other"

    def leaves(root):
        out, stack, seen = [], [root], set()
        while stack and len(out) < MAX_CRIT:
            node = stack.pop(0)
            if node in seen:
                continue
            seen.add(node)
            r = tree.get(node)
            if r and int(r["CriteriaID"] or 0):
                out.append(r)
            stack[0:0] = [int(c["ID"]) for c in kids.get(node, [])]
        return out

    guides = collections.defaultdict(list)
    nsteps = nloc = 0
    for a in sorted(ach, key=lambda r: (int(r["Category"] or 0), int(r["Ui_order"] or 0), int(r["ID"]))):
        aid = int(a["ID"])
        title = achname[aid] or f"Achievement {aid}"
        fac = {"0": "Horde", "1": "Alliance"}.get(a["Faction"], "")
        ftag = f"FACTION|{fac}|" if fac else ""
        body = []
        for leaf in leaves(int(a["Criteria_tree"] or 0)):
            c = crit.get(int(leaf["CriteriaID"]))
            ctid = int(leaf["ID"])
            desc = clean(leaf["Description_lang"])
            if c and c["Type"] == "27" and int(c["Asset"] or 0):
                q = int(c["Asset"])
                name = qnames.get(q, (None,))[0] or desc or f"Quest {q}"
                loc = located(qlines.get(q, []))
                where = f"M|{loc[0]}|Z|{loc[1]}|" if loc else ""
                nloc += bool(loc)
                body.append(f"C {clean(name)}|QID|{q}|ACH|{aid};{ctid}|{where}{ftag}N|{lua_str(title)}: complete this quest.|")
            elif c and c["Type"] == "8" and int(c["Asset"] or 0):
                sub = int(c["Asset"])
                body.append(f"C {achname.get(sub) or desc or 'Achievement %d' % sub}|ACH|{sub}|{ftag}N|Needed for {lua_str(title)}.|")
            else:
                body.append(f"C {desc or title}|ACH|{aid};{ctid}|{ftag}N|{lua_str(title)} criterion.|")
        body.append(f"C {title}|ACH|{aid}|FIXED|{ftag}N|{lua_str(clean(a['Description_lang']))} ({a['Points']} pts)|")
        guides[catpath(int(a["Category"] or 0))].extend(body)
        nsteps += len(body)
    lines = header(fl, "achievements")
    for name in sorted(guides):
        gid = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
        lines.append(f'R({{ id="ach:{fl}:{gid}", name="{lua_str(name)}", type="Achievements", '
                     f'author="Blizzard achievement data", source="CompletionRoute", text=[==[')
        lines.extend(l.replace("]==]", "] ==]") for l in guides[name])
        lines.append("]==] })")
    out = GUIDES / f"Imported_Achievements_{fl}.lua"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{fl}: {len(ach)} achievements -> {len(guides)} category guides, {nsteps} steps "
          f"({nloc} quest criteria located) -> {out.relative_to(ROOT)}")


def gen_storylines(qnames):
    ql = {int(r["ID"]): r for r in rows("retail", "QuestLine")}
    members = collections.defaultdict(list)
    for r in rows("retail", "QuestLineXQuest"):
        members[int(r["QuestLineID"])].append((int(r["OrderIndex"] or 0), int(r["QuestID"])))
    qlines = quest_lines("retail")
    lines = header("retail", "storylines")
    ng = nsteps = bare = 0
    for lid in sorted(members):
        qs = [q for _, q in sorted(members[lid])]
        name = clean(ql.get(lid, {}).get("Name_lang")) or f"Storyline {lid}"
        body, prev, zone = [], None, None
        for q in qs:
            src = qlines.get(q)
            nm = qnames.get(q, (None,))[0] or f"Quest {q}"
            if not src:
                bare += 1
                src = [f"A {nm}|QID|{q}|N|No map pin in client data - follow the story.|", f"T {nm}|QID|{q}|"]
            for l in src:
                if prev and l.startswith("A ") and "|PRE|" not in l:
                    l = l.replace(f"|QID|{q}|", f"|QID|{q}|PRE|{prev}|", 1)
                if zone is None:
                    m = re.search(r"\|Z\|(\d+);", l)
                    zone = m.group(1) if m else None
                body.append(l)
            prev = q
        ng += 1
        nsteps += len(body)
        z = f"zone={zone}, " if zone else ""
        lines.append(f'R({{ id="story:retail:{lid}", name="{lua_str(name)}", type="Storylines", {z}'
                     f'author="Blizzard quest-line data", source="CompletionRoute", text=[==[')
        lines.extend(body)
        lines.append("]==] })")
    out = GUIDES / "Imported_Storylines_retail.lua"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"retail: {ng} storylines, {nsteps} steps ({bare} quests without a pin) -> {out.relative_to(ROOT)}")


# mission tables: GarrTypeID -> [(title, faction, zone step)]
TABLES = {
    "2": [("Garrison Missions (Alliance)", "Alliance", "R Lunarfall garrison mission table|Z|582; Lunarfall|FACTION|Alliance|"),
          ("Garrison Missions (Horde)", "Horde", "R Frostwall garrison mission table|Z|590; Frostwall|FACTION|Horde|")],
    "3": [("Order Hall Missions", "", "R Your class order hall (portal in Dalaran)|Z|627; Dalaran|N|The mission table is in your class order hall.|")],
    "9": [("War Campaign Missions (Alliance)", "Alliance", "R Boralus war table|Z|1161; Boralus|FACTION|Alliance|"),
          ("War Campaign Missions (Horde)", "Horde", "R Dazar'alor war table|Z|1165; Dazar'alor|FACTION|Horde|")],
    "111": [("Covenant Adventures", "", "R Your covenant sanctum (from Oribos)|Z|1670; Oribos|N|The adventure table is in your covenant sanctum.|")],
}


def gen_missions():
    ms = rows("retail", "GarrMission")
    by = collections.defaultdict(list)
    for r in ms:
        by[r["GarrTypeID"]].append(r)
    lines = header("retail", "missions")
    n = 0
    for gt, tabs in TABLES.items():
        for title, fac, first in tabs:
            ftag = f"FACTION|{fac}|" if fac else ""
            body = [first]
            for r in sorted(by.get(gt, []), key=lambda r: (int(r["TargetLevel"] or 0), int(r["ID"]))):
                hrs = int(r["MissionDuration"] or 0) / 3600
                kind = "Shipyard" if r["GarrFollowerTypeID"] == "2" else "Mission"
                body.append(f"N {clean(r['Name_lang']) or 'Mission %s' % r['ID']}|MISSION|{r['ID']}|{ftag}"
                            f"N|{kind} lvl {r['TargetLevel']}, {r['MaxFollowers']} followers, {hrs:g} h, cost {r['MissionCost']}. "
                            f"{clean(r['Location_lang'])}|")
                n += 1
            lines.append(f'R({{ id="mission:retail:{gt}:{fac or "all"}", name="{lua_str(title)}", type="Missions", '
                         f'{("faction=%s, " % repr(fac).replace(chr(39), chr(34))) if fac else ""}'
                         f'author="Blizzard mission data", source="CompletionRoute", text=[==[')
            lines.extend(body)
            lines.append("]==] })")
    left = [gt for gt in by if gt not in TABLES]
    out = GUIDES / "Imported_Missions_retail.lua"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"retail: {len(ms)} missions -> {n} mission steps (unmapped table types: {left}) -> {out.relative_to(ROOT)}")


def main():
    fls = sys.argv[1:] or ["retail", "mop"]
    qn = questie_names()
    for fl in fls:
        gen_achievements(fl, qn)
        if fl == "retail":
            gen_storylines(qn)
            gen_missions()


if __name__ == "__main__":
    main()
