#!/usr/bin/env python3
"""Generate tools/maps_<flavor>.lua (offline zone->world transforms) from wago.tools UiMap + UiMapAssignment.

    python3 tools/gen_maps.py era 1.15.7.61582 tbc 2.5.6.69110 mop 5.5.4.69383 retail 12.1.0.69382

Used by tools/route_sweep.lua to route every guide in every zone without a game client.
Entry: [uiMapID] = { name, instanceID, topX, leftY, width(yRange), height(xRange), parent, mapType }
World convention (matches HereBeDragons): wx = topX - y01*height ; wy = leftY - x01*width.
"""
import csv, io, subprocess, sys

def fetch(table, build):
    url = f"https://wago.tools/db2/{table}/csv?build={build}"
    # curl: wago answers 403 to urllib's default User-Agent
    data = subprocess.run(["curl", "-sS", "-L", "-m", "90", "-A", "CompletionRoute-tools/1.0", url], check=True, capture_output=True).stdout
    return list(csv.DictReader(io.StringIO(data.decode("utf-8"))))

def main(argv):
    pairs = list(zip(argv[::2], argv[1::2]))
    for flavor, build in pairs:
        ui = {r["ID"]: r for r in fetch("UiMap", build)}
        asg = fetch("UiMapAssignment", build)
        best = {}
        for r in asg:
            mid = r["UiMapID"]
            if mid not in ui: continue
            # prefer OrderIndex 0 / the largest region for the map
            x0, y0, x1, y1 = float(r["Region_0"]), float(r["Region_1"]), float(r["Region_3"]), float(r["Region_4"])
            umin0, umin1, umax0, umax1 = float(r["UiMin_0"]), float(r["UiMin_1"]), float(r["UiMax_0"]), float(r["UiMax_1"])
            if umax0 - umin0 <= 0 or umax1 - umin1 <= 0: continue
            # extrapolate the region to the full 0..1 ui square
            w = (y1 - y0) / (umax0 - umin0); h = (x1 - x0) / (umax1 - umin1)   # width along map-x == world y
            leftY = y1 + umin0 * w; topX = x1 + umin1 * h
            area = abs(w * h)
            key = (int(r["OrderIndex"]) != 0, -area)
            if mid not in best or key < best[mid][0]:
                best[mid] = (key, int(r["MapID"]), topX, leftY, w, h)
        out = ["-- GENERATED by tools/gen_maps.py from wago.tools UiMap/UiMapAssignment build %s. Offline use only." % build,
               "return {"]
        n = 0
        for mid, (_, inst, topX, leftY, w, h) in sorted(best.items(), key=lambda kv: int(kv[0])):
            u = ui[mid]
            name = (u.get("Name_lang") or "").replace("\\", "\\\\").replace('"', '\\"')
            out.append('  [%s] = { "%s", %d, %.2f, %.2f, %.2f, %.2f, %s, %s },' % (mid, name, inst, topX, leftY, w, h, u.get("ParentUiMapID") or 0, u.get("Type") or 0))
            n += 1
        # maps with no usable UiMapAssignment (dungeon floors, scenarios...) still exist in the
        # client's C_Map, so ship them name-only: zone-name resolution must match in-game even
        # though there is no world transform to route or measure with (false = "no transform").
        n2 = 0
        for mid in sorted(ui, key=int):
            if mid in best: continue
            u = ui[mid]
            name = (u.get("Name_lang") or "").replace("\\", "\\\\").replace('"', '\\"')
            if not name: continue
            out.append('  [%s] = { "%s", -1, false, false, false, false, %s, %s },' % (mid, name, u.get("ParentUiMapID") or 0, u.get("Type") or 0))
            n2 += 1
        out.append("}")
        path = f"tools/maps_{flavor}.lua"
        open(path, "w").write("\n".join(out) + "\n")
        print(f"{flavor} {build}: {n} maps + {n2} name-only -> {path}")

if __name__ == "__main__":
    main(sys.argv[1:])
