#!/usr/bin/env python3
# CompletionRoute :: tools/gen_entrances.py
# Copyright (c) 2026 Daniel Bates / BatesAI. All rights reserved.
# Licensed under PolyForm Noncommercial 1.0.0 + 10% commercial-revenue rider (see LICENSE).
# https://batesai.org  help@batesai.org
"""Seed dungeon/raid entrances so a step inside an instance routes to its door from the first login.

    python3 tools/gen_entrances.py "<Questie addon dir>"

Core/Instances.lua learns entrances as you walk through them and asks retail's Encounter Journal, but a
fresh character on a Classic client knows none, so every in-dungeon step was "no route" (the bulk of the
0.9% no_route in the virtual-player sweep).  Questie's Database/Zones/data/dungeons.lua lists each
instance's outdoor entrance: this writes CompletionRoute/Data/Imported_Entrances.lua,
    NS.EntranceSeed = { ["The Slave Pens"] = { <outdoor uiMapID>, x01, y01 }, ... }
keyed by the interior map NAME (so every floor of a multi-level dungeon resolves) with the outdoor map
id for the running flavor (Classic ids for era/tbc, modern ids for mop/retail).  Learned and journal
entrances still win; the seed is the last fallback.  Questie is GPL: the output is gitignored.
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "CompletionRoute" / "Data" / "Imported_Entrances.lua"


def area_map(path):
    out = {}
    for m in re.finditer(r"\[(\d+)\]\s*=\s*(\d+),\s*--\s*([^\r\n]+)", path.read_text(encoding="utf-8")):
        a, u = int(m.group(1)), int(m.group(2))
        if u > 0 and a not in out:
            out[a] = u
    return out


def parse(txt, cata):
    base = {}
    for m in re.finditer(r'^\s*\[(\d+)\]\s*=\s*\{"((?:[^"\\]|\\.)*)",[^,]*,(\d+),\{\{(\d+),\s*([\d.]+),\s*([\d.]+)\}', txt, re.M):
        base[int(m.group(1))] = [m.group(2), int(m.group(4)), float(m.group(5)), float(m.group(6))]
    blocks = re.split(r"^if Expansions\.Current >= Expansions\.(\w+) then", txt, flags=re.M)
    for i in range(1, len(blocks), 2):
        exp, body = blocks[i], blocks[i + 1].split("\nend", 1)[0]
        if exp == "Wotlk" or (exp == "Cata" and cata):
            for m in re.finditer(r"dungeons\[(\d+)\]\[4\]\s*=\s*\{\{(\d+),\s*([\d.]+),\s*([\d.]+)\}", body):
                d = int(m.group(1))
                if d in base:
                    base[d][1:] = [int(m.group(2)), float(m.group(3)), float(m.group(4))]
    return base


def main():
    q = Path(sys.argv[1] if len(sys.argv) > 1 else
             "/Volumes/x10/Video Games/Mac/World of Warcraft/_classic_era_/Interface/AddOns/Questie")
    zd = q / "Database" / "Zones" / "data"
    txt = (zd / "dungeons.lua").read_text(encoding="utf-8")
    classic, modern = area_map(zd / "areaIdToUiMapId.lua"), area_map(zd / "MoP" / "areaIdToUiMapId.lua")
    lines = ["-- AUTO-GENERATED by tools/gen_entrances.py from Questie's dungeons.lua (GPL) - local use only, gitignored.",
             "local _, NS = ...", "local seed = {"]
    total = 0
    for fl, amap, cata in (("era", classic, False), ("tbc", classic, False), ("mop", modern, True), ("retail", modern, True)):
        rows = []
        for _, (name, zone, x, y) in sorted(parse(txt, cata).items()):
            if zone in amap:
                rows.append(f'    [{json.dumps(name)}] = {{ {amap[zone]}, {x/100:.4f}, {y/100:.4f} }},')
        lines.append(f"  {fl} = {{")
        lines.extend("  " + r for r in rows)
        lines.append("  },")
        total += len(rows)
        print(f"{fl}: {len(rows)} entrances")
    lines += ["}", "NS.EntranceSeed = seed[NS.flavor] or {}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({total} rows)")


if __name__ == "__main__":
    main()
