#!/usr/bin/env python3
"""Turn roads recorded in game (/cr road) into a shareable Data/Roads_traced.lua.

    python3 tools/roads_from_trace.py "<WoW>/_classic_/WTF/Account/<ACCT>/SavedVariables/CompletionRoute.lua" [more.lua ...]
        [-o CompletionRoute/Data/Roads_traced.lua] [--tolerance 6]

Reads CompletionRouteDB.roadTrace[instance] = { {{wx,wy},...}, ... }, simplifies every segment with
Douglas-Peucker (default 6 yd), drops near-duplicate segments, and writes world-coordinate road entries.
Pure text parsing - no Lua interpreter needed.
"""
import argparse, math, re, sys

def parse_traces(text):
    """Return {inst: [[(x,y),...], ...]} from the SavedVariables dump."""
    m = re.search(r'\["roadTrace"\]\s*=\s*\{', text)
    if not m: return {}
    i = m.end() - 1; depth = 0; j = i
    while j < len(text):
        if text[j] == '{': depth += 1
        elif text[j] == '}':
            depth -= 1
            if depth == 0: break
        j += 1
    body = text[i:j + 1]
    out = {}
    for inst_m in re.finditer(r'\[(\d+)\]\s*=\s*\{', body):
        inst = int(inst_m.group(1))
        # find the balanced block for this instance
        k = inst_m.end() - 1; depth = 0; e = k
        while e < len(body):
            if body[e] == '{': depth += 1
            elif body[e] == '}':
                depth -= 1
                if depth == 0: break
            e += 1
        block = body[k:e + 1]
        segs = []
        # segments are { {x,y}, {x,y}, ... } : collect point pairs per segment
        for seg_m in re.finditer(r'\{\s*((?:\{\s*-?[\d.]+\s*,\s*-?[\d.]+\s*\}\s*,?\s*)+)\}', block):
            pts = [(float(a), float(b)) for a, b in re.findall(r'\{\s*(-?[\d.]+)\s*,\s*(-?[\d.]+)\s*\}', seg_m.group(1))]
            if len(pts) >= 2: segs.append(pts)
        if segs: out[inst] = segs
    return out

def dp(pts, tol):
    if len(pts) < 3: return pts
    ax, ay = pts[0]; bx, by = pts[-1]
    dx, dy = bx - ax, by - ay; L = math.hypot(dx, dy) or 1e-9
    best, bi = 0, 0
    for i in range(1, len(pts) - 1):
        px, py = pts[i]
        d = abs(dx * (ay - py) - (ax - px) * dy) / L
        if d > best: best, bi = d, i
    if best > tol:
        return dp(pts[:bi + 1], tol)[:-1] + dp(pts[bi:], tol)
    return [pts[0], pts[-1]]

def seg_len(p):
    return sum(math.hypot(p[i+1][0]-p[i][0], p[i+1][1]-p[i][1]) for i in range(len(p)-1))

def near_dup(a, b, tol=30):
    """True if every vertex of a lies within tol of some vertex of b (a is covered by b)."""
    return all(any(math.hypot(x-bx, y-by) <= tol for bx, by in b) for x, y in a)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('files', nargs='+'); ap.add_argument('-o', default='CompletionRoute/Data/Roads_traced.lua')
    ap.add_argument('--tolerance', type=float, default=6.0)
    a = ap.parse_args()
    merged = {}
    for f in a.files:
        for inst, segs in parse_traces(open(f, encoding='utf-8', errors='replace').read()).items():
            merged.setdefault(inst, []).extend(segs)
    total_in = sum(len(s) for v in merged.values() for s in v)
    lines = ['-- GENERATED by tools/roads_from_trace.py from in-game road traces. World coordinates. Regenerate, do not hand-edit.',
             'local ADDON, NS = ...', 'NS.RoadData = NS.RoadData or {}', 'local R = NS.RoadData']
    kept = 0; pts_out = 0
    for inst in sorted(merged):
        segs = [dp(s, a.tolerance) for s in merged[inst]]
        segs.sort(key=seg_len, reverse=True)
        out = []
        for s in segs:
            if seg_len(s) < 60: continue
            if any(near_dup(s, o) for o in out): continue
            out.append(s)
        for s in out:
            kept += 1; pts_out += len(s)
            body = ', '.join('{%d,%d}' % (round(x), round(y)) for x, y in s)
            lines.append('R[#R+1] = { inst = %d, name = "traced road", w = { %s } }' % (inst, body))
    open(a.o, 'w').write('\n'.join(lines) + '\n')
    print(f'{total_in} recorded points -> {kept} roads / {pts_out} vertices -> {a.o}')
    if kept: print('Add  Data\\Roads_traced.lua  to CompletionRoute.toc after Roads_kalimdor.lua if it is not there yet.')

if __name__ == '__main__': main()
